framework:
    router:
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        # For API-only applications, this can be set to a default or removed
        default_uri: 'http://localhost'

when@prod:
    framework:
        router:
            strict_requirements: null
